# 1장 벡터, 행렬 그리고 배열

## 1.1 벡터 만들기

In [1]:
# 라이브러리를 임포트합니다.
import numpy as np

In [2]:
np.__version__

'1.15.4'

In [3]:
# 하나의 행으로 벡터를 만듭니다.
vector_row = np.array([1, 2, 3])

In [4]:
vector_row

array([1, 2, 3])

In [5]:
# 하나의 열로 벡터를 만듭니다.
vector_column = np.array([[1],
                          [2],
                          [3]])

In [6]:
vector_column

array([[1],
       [2],
       [3]])

In [7]:
# 넘파이 배열의 클래스를 출력합니다.
print(type(vector_row))

<class 'numpy.ndarray'>


In [8]:
# ndarray를 사용하는 것은 권장되지 않습니다.
bad_way = np.ndarray((3,))

In [9]:
new_row = np.asarray([1, 2, 3])
# asarray()는 새로운 배열을 만들지 않습니다.
new_row = np.asarray(vector_row)
new_row is vector_row

True

In [10]:
# array()는 배열이 입력되면 새로운 배열을 만듭니다.
new_row = np.array(vector_row)
new_row is vector_row

False

In [11]:
# copy() 메서드를 사용하면 의도가 분명해집니다.
new_row = vector_row.copy()
new_row is vector_row

False

## 1-2 행렬 만들기

In [12]:
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [13]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [14]:
# 임의의 값이 채워진 배열을 만듭니다.
empty_matrix = np.empty((3, 2))
empty_matrix

array([[4.65329826e-310, 6.93363467e-310],
       [6.93363232e-310, 6.93363232e-310],
       [6.93363368e-310, 6.93363232e-310]])

In [15]:
zero_matrix = np.zeros((3, 2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
one_matrix = np.ones((3, 2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# 0 행렬을 만든 후 7을 더합니다.
seven_matrix = np.zeros((3, 2)) + 7
# full() 함수를 사용하는 것이 효율적입니다.
seven_matrix = np.full((3, 2), 7)
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])