# 13장. 선형 회귀

이 노트북을 주피터 노트북 뷰어(nbviewer.jupyter.org)로 보거나 구글 코랩(colab.research.google.com)에서 실행할 수 있습니다.

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.jupyter.org/github/rickiepark/machine-learning-with-python-cookbook/blob/master/13.ipynb"><img src="https://jupyter.org/assets/main-logo.svg" width="28" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/machine-learning-with-python-cookbook/blob/master/13.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## 13.1 직선 학습하기

In [1]:
# 라이브러리를 임포트합니다.
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

# 데이터를 로드하고 두 개의 특성만 선택합니다.
boston = load_boston()
features = boston.data[:,0:2]
target = boston.target

# 선형 회귀 모델을 만듭니다.
regression = LinearRegression()

# 선형 회귀 모델을 훈련합니다.
model = regression.fit(features, target)

In [2]:
# 편향을 확인합니다.
model.intercept_

22.485628113468223

In [3]:
# 특성의 계수를 확인합니다.
model.coef_

array([-0.35207832,  0.11610909])

In [4]:
# 타깃 벡터의 첫 번째 값에 1000을 곱합니다.
target[0]*1000

24000.0

In [5]:
# 첫 번째 샘플의 타깃 값을 예측하고 1000을 곱합니다.
model.predict(features)[0]*1000

24573.366631705547

In [6]:
# 첫 번째 계수에 1000을 곱합니다.
model.coef_[0]*1000

-352.07831564026765

### 옮긴이 붙임

In [7]:
regression is model

True

In [8]:
LinearRegression().fit(features, target).predict(features)[0]*1000

24573.366631705547

## 13.2 교차 특성 다루기

In [9]:
# 라이브러리를 임포트합니다.
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

# 데이터를 로드하고 두 개의 특성만 선택합니다.
boston = load_boston()
features = boston.data[:,0:2]
target = boston.target

# 교차 항을 만듭니다.
interaction = PolynomialFeatures(
    degree=3, include_bias=False, interaction_only=True)
features_interaction = interaction.fit_transform(features)

# 선형 회귀 모델을 만듭니다.
regression = LinearRegression()

# 선형 회귀 모델을 훈련합니다.
model = regression.fit(features_interaction, target)

In [10]:
# 첫 번째 샘플의 특성 값을 확인합니다.
features[0]

array([6.32e-03, 1.80e+01])

In [11]:
# 라이브러리를 임포트합니다.
import numpy as np

# 각 샘플에서 첫 번째와 두 번째 특성을 곱합니다.
interaction_term = np.multiply(features[:, 0], features[:, 1])

In [12]:
# 첫 번째 샘플의 교차 항을 확인합니다.
interaction_term[0]

0.11376

In [13]:
# 첫 번째 샘플의 값을 확인합니다.
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

## 13.3 비선형 관계를 학습하기

In [14]:
# 라이브러리를 임포트합니다.
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

# 데이터를 로드하고 하나의 특성을 선택합니다.
boston = load_boston()
features = boston.data[:,0:1]
target = boston.target

# 다항 특성 x^2와 x^3를 만듭니다.
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

# 선형 회귀 모델을 만듭니다.
regression = LinearRegression()

# 선형 회귀 모델을 훈련합니다.
model = regression.fit(features_polynomial, target)

In [15]:
# 첫 번째 샘플을 확인합니다.
features[0]

array([0.00632])

In [16]:
# 첫 번째 샘플을 x^2로 거듭제곱합니다.
features[0]**2

array([3.99424e-05])

In [17]:
# 첫 번째 샘플을 x^2로 세제곱합니다.
features[0]**3

array([2.52435968e-07])

In [18]:
# 첫 번째 샘플의 x, x^2,x^3 값을 확인합니다.
features_polynomial[0]

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

## 13.4 규제로 분산을 줄이기

In [19]:
# 라이브러리를 임포트합니다.
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

# 데이터를 로드합니다.
boston = load_boston()
features = boston.data
target = boston.target

# 특성을 표준화합니다.
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# alpha 값을 지정한 릿지 회귀를 만듭니다.
regression = Ridge(alpha=0.5)

# 선형 회귀 모델을 훈련합니다.
model = regression.fit(features_standardized, target)

In [20]:
# 라이브러리를 임포트합니다.
from sklearn.linear_model import RidgeCV

# 세 개의 alpha 값에 대한 릿지 회귀를 만듭니다.
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

# 선형 회귀 모델을 훈련합니다.
model_cv = regr_cv.fit(features_standardized, target)

# 계수를 확인합니다.
model_cv.coef_

array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [21]:
# alpha 값을 확인합니다.
model_cv.alpha_

1.0

### 옮긴이 붙임

In [22]:
# 5-폴드 교차검증을 사용하여 릿지 회귀를 만듭니다.
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0], cv=5)

# 선형 회귀 모델을 훈련합니다.
model_cv = regr_cv.fit(features_standardized, target)

# alpha 값을 확인합니다.
model_cv.alpha_

/home/haesun/anaconda3/envs/ml-cookbook/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


10.0

## 13.5 라쏘 회귀로 특성 줄이기

In [23]:
# 라이브러리를 임포트합니다.
from sklearn.linear_model import Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

# 데이터를 로드합니다.
boston = load_boston()
features = boston.data
target = boston.target

# 특성을 표준화합니다.
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# alpha 값을 지정한 라쏘 회귀를 만듭니다.
regression = Lasso(alpha=0.5)

# 선형 회귀 모델을 훈련합니다.
model = regression.fit(features_standardized, target)

In [24]:
# 계수를 확인합니다.
model.coef_

array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [25]:
# 큰 alpha 값을 지정한 라쏘 회귀를 만듭니다.
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized, target)
model_a10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])

### 옮긴이 붙임

In [26]:
# 라이브러리를 임포트합니다.
from sklearn.linear_model import LassoCV

# 세 개의 alpha 값에 대한 라쏘 회귀를 만듭니다.
lasso_cv = LassoCV(alphas=[0.1, 1.0, 10.0], cv=5)

# 선형 회귀 모델을 훈련합니다.
model_cv = lasso_cv.fit(features_standardized, target)

# 계수를 확인합니다.
model_cv.coef_

array([-0.63230364,  0.70840931, -0.        ,  0.65760723, -1.57419335,
        2.82626903, -0.        , -2.42207901,  1.19593681, -0.84646778,
       -1.92249345,  0.76216539, -3.72618383])

In [27]:
# alpha 값을 확인합니다.
model_cv.alpha_

0.1

In [28]:
# 1000개의 alpha 값을 탐색하는 라쏘 회귀를 만듭니다.
lasso_cv = LassoCV(n_alphas=1000, cv=5)

# 선형 회귀 모델을 훈련합니다.
model_cv = lasso_cv.fit(features_standardized, target)

# 계수를 확인합니다.
model_cv.alpha_

0.15326173083090813

In [29]:
lasso_cv.alphas_

array([6.77765364e+00, 6.73095006e+00, 6.68456831e+00, 6.63850616e+00,
       6.59276142e+00, 6.54733189e+00, 6.50221542e+00, 6.45740983e+00,
       6.41291299e+00, 6.36872277e+00, 6.32483706e+00, 6.28125375e+00,
       6.23797077e+00, 6.19498605e+00, 6.15229752e+00, 6.10990315e+00,
       6.06780092e+00, 6.02598880e+00, 5.98446481e+00, 5.94322695e+00,
       5.90227325e+00, 5.86160175e+00, 5.82121052e+00, 5.78109761e+00,
       5.74126112e+00, 5.70169913e+00, 5.66240975e+00, 5.62339112e+00,
       5.58464135e+00, 5.54615860e+00, 5.50794102e+00, 5.46998680e+00,
       5.43229411e+00, 5.39486116e+00, 5.35768615e+00, 5.32076731e+00,
       5.28410287e+00, 5.24769107e+00, 5.21153018e+00, 5.17561847e+00,
       5.13995423e+00, 5.10453573e+00, 5.06936130e+00, 5.03442925e+00,
       4.99973792e+00, 4.96528563e+00, 4.93107075e+00, 4.89709163e+00,
       4.86334666e+00, 4.82983422e+00, 4.79655271e+00, 4.76350054e+00,
       4.73067612e+00, 4.69807789e+00, 4.66570428e+00, 4.63355376e+00,
      